# Generated by Django 5.2.5 on 2025-08-08 15:44

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                ("genre", models.CharField(max_length=128)),
                ("description", models.TextField()),
                ("poster", models.ImageField(upload_to="posters/")),
                ("release_date", models.DateField()),
            ],
        ),
    ]
